# Gunakan base image Python versi slim agar hemat ukuran
FROM python:3.10-slim

# Set working directory di dalam container
WORKDIR /app

# Salin dependencies dan install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin seluruh kode proyek ke dalam container
COPY . .

# Expose port aplikasi FastAPI
EXPOSE 8000

# Perintah untuk menjalankan aplikasi
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]