sonar.projectKey=Dapkings_technova-inventory
sonar.organization=dapkings
sonar.sources=.
sonar.exclusions=**/*.yml, **/*.yaml, test_main.py, venv/**, .pytest_cache/**, coverage.xml
sonar.python.coverage.reportPaths=coverage.xml